// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _.Data;

#nullable disable

namespace _.Migrations
{
    [DbContext(typeof(TrialsContext))]
    [Migration("20250407043500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("_.Models.ClinicalTrial", b =>
                {
                    b.Property<string>("NctId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefTitle")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Conditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityCriteria")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderBased")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthyVolunteers")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatePostDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdateSubmitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaximumAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phases")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyFirstPostDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyFirstSubmitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyType")
                        .HasColumnType("TEXT");

                    b.HasKey("NctId");

                    b.ToTable("ClinicalTrials");
                });

            modelBuilder.Entity("_.Models.ClinicalTrial", b =>
                {
                    b.OwnsMany("_.Models.Intervention", "Interventions", b1 =>
                        {
                            b1.Property<string>("ClinicalTrialNctId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .HasColumnType("TEXT");

                            b1.HasKey("ClinicalTrialNctId", "Id");

                            b1.ToTable("Intervention");

                            b1.WithOwner()
                                .HasForeignKey("ClinicalTrialNctId");
                        });

                    b.OwnsMany("_.Models.Location", "Locations", b1 =>
                        {
                            b1.Property<string>("ClinicalTrialNctId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Zip")
                                .HasColumnType("TEXT");

                            b1.HasKey("ClinicalTrialNctId", "Id");

                            b1.ToTable("Location");

                            b1.WithOwner()
                                .HasForeignKey("ClinicalTrialNctId");
                        });

                    b.Navigation("Interventions");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
